pipeline:
  test:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew check
    when:
      event:
        - push
        - pull_request
  build:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew build
    when:
      event:
        - push
        - pull_request
  sonarqube:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew sonarqube
    when:
      event:
        - push
        - pull_request
  docker:
    registry: mccontainerregistry.azurecr.io
    image: plugins/docker
    target: staging
    repo: mccontainerregistry.azurecr.io/multipay/multipay-utility-payments-api
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      event: 
        - push
  consul:
    image: alpine:3.8
    commands:
      - wget https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_amd64.tgz
      - tar xvf consul-template_0.19.5_linux_amd64.tgz
      - ./consul-template -template "secrets-staging.yml.tmpl:secrets-staging.yml" -once
    secrets:
      - source: consul_http_addr
        target: CONSUL_HTTP_ADDR
      - source: consul_http_token
        target: CONSUL_HTTP_TOKEN
    when:
      event: 
        - push
  secrets:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:0.1.4
    cluster: staging
    template: secrets-staging.yml
    when:
      event: 
        - push
  staging:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:0.1.4
    cluster: staging
    template: deployment.yml
    vars:
      - IMAGE=mccontainerregistry.azurecr.io/multipay/multipay-utility-payments-api:${DRONE_COMMIT_SHA}
    when:
      branch: master
      event:
        - push
  slack:
    image: mccontainerregistry.azurecr.io/tools/drone-slack:1.0.0
    channel: multipay-ci
    icon_emoji: ":package:"
    when:
      status: 
        - success
        - failure
