pipeline:

  test:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew check
    when:
      event:
        - push
        - pull_request
        - tag

  build:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew build
    when:
      event:
        - push
        - pull_request
        - tag
  
  debug:
    image: openjdk:8-alpine
    commands: 
      - ls -la
      - cd ./build/libs
      - ls -la

  docker:
    registry: mccontainerregistry.azurecr.io
    image: plugins/docker
    repo: mccontainerregistry.azurecr.io/tenpo/tenpo-utility-payments-core
    secrets: 
      - docker_username
      - docker_password
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: 
        - push

  dev_consul:
    image: hashicorp/consul-template:alpine
    commands:
      - /bin/consul-template -template ".kube.secrets.yml.tmpl:.kube.secrets.yml" -once
    environment:
      - ENVIRONMENT=dev
    secrets:
      - consul_http_addr
      - consul_http_token
    when:
      branch: master
      event: 
        - push

  dev_secrets:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: falcon
    template: .kube.secrets.yml
    when:
      branch: master
      event: 
        - push

  dev_virtual_service:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: falcon
    template: .kube.virtual-service.yml
    when:
      branch: master
      event: 
        - push

  dev_deployment:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: falcon
    vars:
      - IMAGE=mccontainerregistry.azurecr.io/tenpo/tenpo-utility-payments-core:${DRONE_COMMIT_SHA}
      - ENVIRONMENT=dev
    when:
      branch: master
      event:
        - push

  slack:
    image: mccontainerregistry.azurecr.io/tools/drone-slack:1.0.0
    channel: tenpo-ci
    icon_emoji: ":package:"
    when:
      status: 
        - success
        - failure