pipeline:
  test:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew check
    when:
      event:
        - push
        - pull_request
  build:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew build
    when:
      event:
        - push
        - pull_request
  sonarqube:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew sonarqube
    when:
      event:
        - push
        - pull_request
  migrate:
    image: alpine:3.8
    commands:
      - cd database
      - wget https://github.com/amacneil/dbmate/releases/download/v1.4.1/dbmate-linux-musl-amd64
      - chmod +x dbmate-linux-musl-amd64
      - wget https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_amd64.tgz
      - tar xvf consul-template_0.19.5_linux_amd64.tgz
      - ./consul-template -template ".env-staging.tmpl:.env" -once
      - cat .env
      #- ./dbmate-linux-musl-amd64 up
    secrets:
      - source: consul_http_addr
        target: CONSUL_HTTP_ADDR
      - source: consul_http_token
        target: CONSUL_HTTP_TOKEN
    when:
      event:
        - push
  slack:
    image: mccontainerregistry.azurecr.io/tools/drone-slack:1.0.0
    channel: multipay-ci
    icon_emoji: ":package:"
    when:
      status: 
        - success
        - failure
