pipeline:
  test:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew check
    when:
      event:
        - push
        - pull_request
  build:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew build
    when:
      event:
        - push
        - pull_request
  # sonarqube:
  #   image: openjdk:8-alpine
  #   environment:
  #     - GRADLE_USER_HOME=~/.gradle
  #   commands:
  #     - ./gradlew sonarqube
  #   when:
  #     event:
  #       - push
  #       - pull_request
  migrate:
    image: alpine:3.8
    commands:
      - cd database
      - wget https://github.com/amacneil/dbmate/releases/download/v1.4.1/dbmate-linux-musl-amd64
      - ls -la
      - rm -f dbmate
      - rm -f .env
      - chmod +x dbmate-linux-musl-amd64
      - ./dbmate-linux-musl-amd64 up
    when:
      event:
        - push
  slack:
    image: mccontainerregistry.azurecr.io/tools/drone-slack:1.0.0
    channel: multipay-ci
    icon_emoji: ":package:"
    when:
      status: 
        - success
        - failure