pipeline:
  test:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew check
    when:
      event:
        - push
        - pull_request
        - tag

  build:
    image: openjdk:8-alpine
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew build
    when:
      event:
        - push
        - pull_request
        - tag

  docker:
    registry: mccontainerregistry.azurecr.io
    image: plugins/docker
    target: staging
    repo: mccontainerregistry.azurecr.io/tenpo/tenpo-utility-payments-api
    secrets: 
      - docker_username
      - docker_password
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: 
        - push

  slack:
    image: mccontainerregistry.azurecr.io/tools/drone-slack:1.0.0
    channel: tenpo-ci
    icon_emoji: ":package:"
    when:
      status: 
        - success
        - failure