stages:
- test
- build
- docker
- deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test:
  stage: test
  image: openjdk:8-alpine
  variables:
    GRADLE_USER_HOME: ~/.gradle
  script:
    - ./gradlew check
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle

build:
  stage: build
  image: openjdk:8-alpine
  variables:
    GRADLE_USER_HOME: ~/.gradle
  script:
    - ./gradlew build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle
  artifacts:
    paths:
      - build/libs
    expire_in: 1 week

docker:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script: 
    - docker info
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $GITLAB_REGISTRY .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
