stages:
  - build
  - docker
  - consul
  - deploy

build:
  stage: build
  image: openjdk:8-alpine
  variables:
    GRADLE_USER_HOME: ~/.gradle
  script:
    - ./gradlew build -x test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle
      - build

kiuwan:
  stage: build
  image: registry.gitlab.com/krealomine/deploy_docker_kiuwan:lastest
  script:
    - ${HOME}/KiuwanLocalAnalyzer/bin/agent.sh -n ${CI_PROJECT_NAME} -s ${CI_PROJECT_DIR} -l "GitLab build ${CI_JOB_ID}" -c --user ${KIUWAN_USER} --pass ${KIUWAN_PASSWD}
  only:
    - develop

dev_docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  only:
    - develop
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - build

dev_consul:
  stage: consul
  image: hashicorp/consul-template:alpine
  environment:
    name: dev
  variables:
    ENVIRONMENT: dev
  script:
    - /bin/consul-template -template ".kube.secrets.yml.tmpl:.kube.secrets.yml" -once
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle
      - build
      - .kube.secrets.yml
  only:
    - develop

dev_secrets:
  stage: deploy
  image: registry.gitlab.com/krealomine/deploy_k8s_azure:latest
  environment:
    name: dev
  script:
    - kubectl apply -f .kube.secrets.yml
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .kube.secrets.yml
  only:
    - develop

dev_deployment:
  stage: deploy
  image: registry.gitlab.com/krealomine/deploy_k8s_azure:latest
  environment:
    name: dev
  variables:
    ENVIRONMENT: dev
    REGISTRY: tenpo-utility-payments-core-registry
    NAMESPACE: tenpo-utility-payments
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    INTERNAL_BALANCER: "false"
  script:
    - sed -i "s|_IMAGE_|$IMAGE|g" .kube.yml
    - sed -i "s|_ENVIRONMENT_|$ENVIRONMENT|g" .kube.yml
    - sed -i "s|_INTERNAL_BALANCER_|$INTERNAL_BALANCER|g" .kube.yml
    - > 
        kubectl create secret docker-registry $REGISTRY \
          --namespace=$NAMESPACE \
          --dry-run=true \
          --docker-server=$CI_REGISTRY \
          --docker-username=$CI_DEPLOY_USER \
          --docker-password=$CI_DEPLOY_PASSWORD \
          --docker-email=$GITLAB_USER_EMAIL -o yaml | kubectl apply -f -
    - kubectl apply -f .kube.yml
  only:
    - develop

uat_docker:
  extends: dev_docker
  only:
    - uat

uat_consul:
  extends: dev_consul
  environment:
    name: uat
  variables:
    ENVIRONMENT: uat
  only:
    - uat

uat_secrets:
  extends: dev_secrets
  image: registry.gitlab.com/krealomine/deploy_k8s_azure_uat:latest
  environment:
    name: uat
  only:
    - uat

uat_deployment:
  extends: dev_deployment
  image: registry.gitlab.com/krealomine/deploy_k8s_azure_uat:latest
  environment:
    name: uat
  variables:
    ENVIRONMENT: uat
    REGISTRY: tenpo-utility-payments-core-registry
    NAMESPACE: tenpo-utility-payments
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    INTERNAL_BALANCER: "true"
  only:
    - uat

prod_docker:
  extends: dev_docker
  before_script: 
    - rm ./docker/Dockerfile
    - mv ./docker/prod/Dockerfile ./docker/Dockerfile
  only:
    - master

prod_consul:
  extends: dev_consul
  environment:
    name: prod
  variables:
    ENVIRONMENT: prod
  script:
    - export CONSUL_HTTP_ADDR=$CONSUL_HTTP_ADDR_PROD
    - export CONSUL_HTTP_TOKEN=$CONSUL_HTTP_TOKEN_PROD
    - /bin/consul-template -template ".kube.secrets.yml.tmpl:.kube.secrets.yml" -once
  only:
    - master

prod_secrets:
  extends: dev_secrets
  image: registry.gitlab.com/krealomine/deploy_k8s_azure_prod:latest
  environment:
    name: prod
  only:
    - master

prod_deployment:
  extends: dev_deployment
  image: registry.gitlab.com/krealomine/deploy_k8s_azure_prod:latest
  environment:
    name: prod
  variables:
    ENVIRONMENT: prod
    REGISTRY: tenpo-utility-payments-core-registry
    NAMESPACE: tenpo-utility-payments
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    INTERNAL_BALANCER: "true"
  only:
    - master
