stages:
- test
- build
- docker
- deploy

test:
  stage: test
  image: openjdk:8-alpine
  variables:
    GRADLE_USER_HOME: ~/.gradle
  script:
    - ./gradlew check
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle

build:
  stage: build
  image: openjdk:8-alpine
  variables:
    GRADLE_USER_HOME: ~/.gradle
  script:
    - ./gradlew build
    - ls -la
    - ls -la build
    - ls -la build/libs
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle

docker:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script: 
    - docker info
    - docker build -t registry.gitlab.com/krealomine/tenpo-utility-payments-api:$CI_COMMIT_REF_NAME .