---
apiVersion: v1
kind: Namespace
metadata:
  name: tenpo-utility-payments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenpo-utility-payments-core
  namespace: tenpo-utility-payments
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: tenpo-utility-payments-core
  template:
    metadata:
      namespace: tenpo-utility-payments
      labels:
        app: tenpo-utility-payments-core
        version: v1
    spec:
      containers:
        - name: tenpo-utility-payments-core
          image: _IMAGE_
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: _ENVIRONMENT_
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-core-secrets
                  key: pg_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-core-secrets
                  key: pg_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-core-secrets
                  key: pg_pass
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-core-secrets
                  key: pg_db
          readinessProbe:
            httpGet:
              path: /management/health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /management/health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3  

          imagePullPolicy: Always
      imagePullSecrets:
        - name: tenpo-utility-payments-core-registry
---
apiVersion: crds.tenpo.cl/v1alpha1
kind: TenpoService
metadata:
  name: tenpo-utility-payments-ts
  namespace: tenpo-utility-payments
spec:
  selector:
    app: tenpo-utility-payments-core #Selector must match with deployment's app label
  networking:
    host: _HOST_
    port: 80
    protocol: TCP
    endpoints:
      - name: welcome
        path: /v1/utility-payments/welcome(.*)
        profile: private
        methods:
          - POST
      - name: categories
        path: /v1/utility-payments/categories(.*)
        profile: private
        methods:
          - GET
      - name: utilities
        path: /v1/utility-payments/utilities(.*)
        profile: private
        methods:
          - POST
      - name: bills
        path: /v1/utility-payments/bills(.*)
        profile: private
        methods:
            - GET
      - name: transactions
        path: /v1/utility-payments/transactions(.*)
        profile: private
        methods:
            - POST
      - name: favorites
        path: /v1/utility-payments/favorites(.*)
        profile: private
        methods:
            - POST  
            - GET
            - DELETE
      - name: options
        path: /v1/utility-payments/options(.*)
        profile: private
        methods: 
            - GET
            - PUT
      - name: suggestions
        path: /v1/utility-payments/suggestions(.*)
        profile: private
        methods: 
            - GET
            - DELETE
      - name: home
        path: /v1/utility-payments/home
        profile: private
        methods: 
            - GET
      - name: main-screen
        path: /v1/utility-payments/main-screen
        profile: private
        methods: 
            - GET                                                                      
  teamInfo:
    name: Sheldon
    slackChannel: "#sheldon"
