---
apiVersion: v1
kind: Namespace
metadata:
  name: tenpo
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenpo-utility-payments-api
  namespace: tenpo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenpo-utility-payments-api
  template:
    metadata:
      namespace: tenpo
      labels:
        app: tenpo-utility-payments-api
        version: v1
    spec:
      containers:
        - name: tenpo-utility-payments-api
          image: ${IMAGE}
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ${ENVIRONMENT}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-api-secrets
                  key: pg_login
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-api-secrets
                  key: pg_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-api-secrets
                  key: pg_name
            - name: DB_FQDN
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-api-secrets
                  key: pg_fqdn
          imagePullPolicy: Always
      imagePullSecrets:
        - name: container-reg-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: tenpo-utility-payments-api-svc
  namespace: tenpo
  labels:
    app: tenpo-utility-payments-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: tenpo-utility-payments-api
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tenpo-utility-payments-api-se-mail
  namespace: tenpo
spec:
  hosts:
    - smtp.sendgrid.net
  location: MESH_EXTERNAL
  ports:
    - number: 587
      name: tcp-smtp
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tenpo-utility-payments-api-se-db
  namespace: tenpo
spec:
  hosts:
    - "*.database.azure.com"
  location: MESH_EXTERNAL
  ports:
    - number: 5432
      name: tcp-db
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tenpo-utility-payments-api-pdc
  namespace: tenpo
spec:
  hosts:
    - "*.multicaja.cl"
    - "*.mcdesaqa.cl"
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: tcp-pdc
      protocol: TCP