---
apiVersion: v1
kind: Namespace
metadata:
  name: tenpo-utility-payments
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenpo-utility-payments-core
  namespace: tenpo-utility-payments
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: tenpo-utility-payments-core
  template:
    metadata:
      namespace: tenpo-utility-payments
      labels:
        app: tenpo-utility-payments-core
        version: v1
    spec:
      containers:
        - name: tenpo-utility-payments-core
          image: _IMAGE_
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: _ENVIRONMENT_
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-core-secrets
                  key: pg_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-core-secrets
                  key: pg_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-core-secrets
                  key: pg_pass
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tenpo-utility-payments-core-secrets
                  key: pg_db
          readinessProbe:
            httpGet:
              path: /management/health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /management/health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3  

          imagePullPolicy: Always
      imagePullSecrets:
        - name: tenpo-utility-payments-core-registry
---
apiVersion: v1
kind: Service
metadata:
  name: tenpo-utility-payments-core-svc
  namespace: tenpo-utility-payments
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "_INTERNAL_BALANCER_"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: tenpo-utility-payments-core