---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tenpo-utility-payments-api-vts-back
  namespace: tenpo
spec:
  hosts:
    - tenpo.${CLUSTER_ENVIRONMENT}.${CLUSTER_DOMAIN}
  gateways:
    - global-gateway.default.svc.cluster.local
  http:
    - match:
      - uri:
          prefix: /utility-payments
      route:
      - destination:
          host: tenpo-utility-payments-api-svc
          port:
            number: 80