version: '3'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=multipay
      - POSTGRES_USER=multipay
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.cl
      - PGADMIN_DEFAULT_PASSWORD=testtest