version: '3'
services:
  stan:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      VAR: VALUE
    command:
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-DV"
      # - "-SDV"
      - "-store"
      - "file"
      - "-dir"
      - "datastore"
      - "-cid"
      - "tenpo-utility-payment-cluster"