openapi: 3.0.1
info:
  title: Utility Payments
  version: 1.0.0
servers:
  - url: https://tenpo.staging.multicajadigital.cloud
tags:
  - name: utility payments
    description: Operaciones de pago de cuenta
paths:

  /utility-payments/v1/categories:
    get:
      tags: 
        - utility payments
      summary: Obtiene las categorías de los convenios pagos de cuenta
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /utility-payments/v1/payment-methods:
    get:
      tags: 
        - utility payments
      summary: Obtiene los métodos de pago disponibles
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentMethod'

  /utility-payments/v1/utilities:
    get:
      tags: 
        - utility payments
      summary: Obtiene los convenios de pago de cuenta
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utility'

  /utility-payments/v1/bills:
    post:
      tags:
        - utility payments
      summary: Obtiene las deudas de un identificador de pago de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillRequest'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BillResponse'

  /utility-payments/v1/transactions:
    post:
      tags: 
        - utility payments
      summary: Crea una transacción de pago de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'

  /utility-payments/v1/transactions/{id}:
    get:
      tags: 
        - utility payments
      summary: Obtiene los detalles de una transacción de pago de cuenta
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Id de la transacción de pago de cuenta
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'

  /utility-payments/v1/transactions/{id}/receipt:
    post:
      tags: 
        - utility payments
      summary: Reenvía el comprobante de una transacción de pago de cuenta
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Id de la transacción de pago de cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReceiptRequest'
      responses:
        200:
          description: successful operation
          
components:
  schemas:
    
    Utility:
      type: object
      properties:
        utility_code:
          type: string
          example: MUNDO_PACIFICO
        utility_name:
          type: string
          example: Mundo Pacífico
        collector_id:
          type: string
          example: 1
        collector_name:
          type: string
          example: "OTRO"
        category_id:
          type: string
          example: 100
        category_name:
          type: string
          example: AGUA
        identifiers:
          type: array
          items:
            type: string
          example: ["RUT", "CON DIGITO VERIFICADOR"]
    
    Category:
      type: object
      properties:
        category_id:
          type: string
          example: 100
        category_name:
          type: string
          example: AGUA
    
    PaymentMethod:
      type: object
      properties:
        payment_method_code:
          type: string
          example: webpay
        payment_method_name:
          type: string
          example: Webpay
    
    BillRequest:
      type: object
      properties:
        utility_code:
          type: string
          example: MUNDO_PACIFICO
        collector_id:
          type: string
          example: 1
        category_id:
          type: string
          example: 100
        identifier:
          type: string
          example: 66823334

    BillResponse:
      type: object
      properties:
        id:
          type: string
          example: "fb7c3a5f-1db0-4ba0-ab72-a58db5f55f10"
        status:
          type: string
          example: WAITING
        utility_code:
          type: string
          example: MUNDO_PACIFICO
        utility_name:
          type: string
          example: Mundo Pacífico
        collector_id:
          type: string
          example: 1
        collector_name:
          type: string
          example: "OTRO"
        category_id:
          type: string
          example: 100
        category_name:
          type: string
          example: AGUA
        identifier:
          type: string
          example: 66823334
        amount: 
          type: integer
          example: 5467
        due_date:
          type: string
          example: No disponible
        description:
          type: string
          example: Deuda Total
    
    TransactionRequest:
      type: object
      properties:
        bill:
          type: string
          example: "fb7c3a5f-1db0-4ba0-ab72-a58db5f55f10"
        email:
          type: string
          example: correo@ejemplo.cl
        payment_method:
          type: string
          example: webpay
    
    TransactionResponse:
      type: object
      properties:
        id:
          type: string
          example: 51d95fc6-58e9-4bb0-a622-031cf08edc9c
        status:
          type: string
          example: WAITING
        order:
          type: string
          example: 120190424105826006
        payment_method:
          type: string
          example: WEBPAY
        amount:
          type: integer
          example: 7639
        email:
          type: string
          example: correo@ejemplo.cl
        created:
          type: string
          example: "2019-04-24T10:58:26.140605-04:00"
        updated:
          type: string
          example: "2019-04-24T10:58:26.140605-04:00"
        bill:
          $ref: '#/components/schemas/BillResponse'
        webpay:
          type: object
          properties:
            id:
              type: string
              example: "1e97647a-e380-4cc8-ba71-6bbd85b5ed07"
            status:
              type: string
              example: WAITING
            url:
              type: string
              example: https://webpay3gint.transbank.cl/webpayserver/initTransaction
            token:
              type: string
              example: e47d8c3c2707730fda36fc15d4418a556e3a1f2bbb7e8cacfff56c0d0bb2d2d0
    
    ReceiptRequest:
      type: object
      properties:
        email:
          type: string
          example: correo@ejemplo.cl
        recaptcha:
          type: string
          example: "03AOLTBLTVBtniCIGwS_N4XFQAQ3d5vXsQJp8kYLRsDcqhBUEf2mh8onvgXDOJ"